---
apiVersion: v1
kind: Service
metadata:
  name: bind9-service
  namespace: dns
spec:
  selector:
    app: bind9
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
      name: tcp
    - protocol: UDP
      port: 53
      targetPort: 53
      name: udp
  externalIPs:
    - 192.168.178.188
